import { AncestorProvider } from "@/provider/UserProvider";
import "./globals.css";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html data-theme="light" lang="en">
      <body>
        <AncestorProvider>{children}</AncestorProvider>
      </body>
    </html>
  );
}
