import { Footer } from "@/components/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <body className="h-screen justify-between flex flex-col">
      <div className="h-[90%]">{children}</div>
      <Footer />
    </body>
  );
}
