import Magicfooter from "@/components/Magicfooter";
import Magicheader from "@/components/Magicheader";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <body className="h-screen justify-between flex flex-col">
      <Magicheader />
      {children}
      <Magicfooter />
    </body>
  );
}
