import { Footer } from "@/components/Footer";
import Header from "@/components/Header";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <body className="flex flex-col h-screen">
      <Header />
      {children}
      <Footer />
    </body>
  );
}
